target-version = "py311"
line-length = 180

[lint]
select = ["E4", "E7", "E9", "F", "I", "UP"]
ignore = [
    "UP006",
    "UP007",
    "UP008",
    "UP009",
    "UP031",
    "UP032",
    "UP034",
    "UP035",
    "UP036",
    "UP045",
]
